// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb_account.proto

package pb_mars

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CMD int32

const (
	CMD_CMD_DEF             CMD = 0
	CMD_CMD_LOGIN_MSG       CMD = 65793
	CMD_CMD_CREATE_ROLE_MSG CMD = 65794
	CMD_CMD_LOAD_USER_MSG   CMD = 65795
	CMD_CMD_SYS_TIME_MSG    CMD = 9437441
)

var CMD_name = map[int32]string{
	0:       "CMD_DEF",
	65793:   "CMD_LOGIN_MSG",
	65794:   "CMD_CREATE_ROLE_MSG",
	65795:   "CMD_LOAD_USER_MSG",
	9437441: "CMD_SYS_TIME_MSG",
}

var CMD_value = map[string]int32{
	"CMD_DEF":             0,
	"CMD_LOGIN_MSG":       65793,
	"CMD_CREATE_ROLE_MSG": 65794,
	"CMD_LOAD_USER_MSG":   65795,
	"CMD_SYS_TIME_MSG":    9437441,
}

func (x CMD) String() string {
	return proto.EnumName(CMD_name, int32(x))
}

func (CMD) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_149270acda60d50e, []int{0}
}

type LoginMsg struct {
	Platform             uint32   `protobuf:"varint,1,opt,name=platform,proto3" json:"platform,omitempty"`
	Account              string   `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginMsg) Reset()         { *m = LoginMsg{} }
func (m *LoginMsg) String() string { return proto.CompactTextString(m) }
func (*LoginMsg) ProtoMessage()    {}
func (*LoginMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_149270acda60d50e, []int{0}
}

func (m *LoginMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginMsg.Unmarshal(m, b)
}
func (m *LoginMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginMsg.Marshal(b, m, deterministic)
}
func (m *LoginMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginMsg.Merge(m, src)
}
func (m *LoginMsg) XXX_Size() int {
	return xxx_messageInfo_LoginMsg.Size(m)
}
func (m *LoginMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginMsg.DiscardUnknown(m)
}

var xxx_messageInfo_LoginMsg proto.InternalMessageInfo

func (m *LoginMsg) GetPlatform() uint32 {
	if m != nil {
		return m.Platform
	}
	return 0
}

func (m *LoginMsg) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *LoginMsg) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginMsgRes struct {
	HasRole              uint32   `protobuf:"varint,1,opt,name=has_role,json=hasRole,proto3" json:"has_role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginMsgRes) Reset()         { *m = LoginMsgRes{} }
func (m *LoginMsgRes) String() string { return proto.CompactTextString(m) }
func (*LoginMsgRes) ProtoMessage()    {}
func (*LoginMsgRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_149270acda60d50e, []int{1}
}

func (m *LoginMsgRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginMsgRes.Unmarshal(m, b)
}
func (m *LoginMsgRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginMsgRes.Marshal(b, m, deterministic)
}
func (m *LoginMsgRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginMsgRes.Merge(m, src)
}
func (m *LoginMsgRes) XXX_Size() int {
	return xxx_messageInfo_LoginMsgRes.Size(m)
}
func (m *LoginMsgRes) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginMsgRes.DiscardUnknown(m)
}

var xxx_messageInfo_LoginMsgRes proto.InternalMessageInfo

func (m *LoginMsgRes) GetHasRole() uint32 {
	if m != nil {
		return m.HasRole
	}
	return 0
}

type CreateRoleMsg struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoleMsg) Reset()         { *m = CreateRoleMsg{} }
func (m *CreateRoleMsg) String() string { return proto.CompactTextString(m) }
func (*CreateRoleMsg) ProtoMessage()    {}
func (*CreateRoleMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_149270acda60d50e, []int{2}
}

func (m *CreateRoleMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoleMsg.Unmarshal(m, b)
}
func (m *CreateRoleMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoleMsg.Marshal(b, m, deterministic)
}
func (m *CreateRoleMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoleMsg.Merge(m, src)
}
func (m *CreateRoleMsg) XXX_Size() int {
	return xxx_messageInfo_CreateRoleMsg.Size(m)
}
func (m *CreateRoleMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoleMsg.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoleMsg proto.InternalMessageInfo

func (m *CreateRoleMsg) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateRoleMsgRes struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoleMsgRes) Reset()         { *m = CreateRoleMsgRes{} }
func (m *CreateRoleMsgRes) String() string { return proto.CompactTextString(m) }
func (*CreateRoleMsgRes) ProtoMessage()    {}
func (*CreateRoleMsgRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_149270acda60d50e, []int{3}
}

func (m *CreateRoleMsgRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoleMsgRes.Unmarshal(m, b)
}
func (m *CreateRoleMsgRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoleMsgRes.Marshal(b, m, deterministic)
}
func (m *CreateRoleMsgRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoleMsgRes.Merge(m, src)
}
func (m *CreateRoleMsgRes) XXX_Size() int {
	return xxx_messageInfo_CreateRoleMsgRes.Size(m)
}
func (m *CreateRoleMsgRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoleMsgRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoleMsgRes proto.InternalMessageInfo

type LoadUserMsg struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadUserMsg) Reset()         { *m = LoadUserMsg{} }
func (m *LoadUserMsg) String() string { return proto.CompactTextString(m) }
func (*LoadUserMsg) ProtoMessage()    {}
func (*LoadUserMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_149270acda60d50e, []int{4}
}

func (m *LoadUserMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadUserMsg.Unmarshal(m, b)
}
func (m *LoadUserMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadUserMsg.Marshal(b, m, deterministic)
}
func (m *LoadUserMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadUserMsg.Merge(m, src)
}
func (m *LoadUserMsg) XXX_Size() int {
	return xxx_messageInfo_LoadUserMsg.Size(m)
}
func (m *LoadUserMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadUserMsg.DiscardUnknown(m)
}

var xxx_messageInfo_LoadUserMsg proto.InternalMessageInfo

type LoadUserMsgRes struct {
	User                 *UserT    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Events               []*EventT `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LoadUserMsgRes) Reset()         { *m = LoadUserMsgRes{} }
func (m *LoadUserMsgRes) String() string { return proto.CompactTextString(m) }
func (*LoadUserMsgRes) ProtoMessage()    {}
func (*LoadUserMsgRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_149270acda60d50e, []int{5}
}

func (m *LoadUserMsgRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadUserMsgRes.Unmarshal(m, b)
}
func (m *LoadUserMsgRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadUserMsgRes.Marshal(b, m, deterministic)
}
func (m *LoadUserMsgRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadUserMsgRes.Merge(m, src)
}
func (m *LoadUserMsgRes) XXX_Size() int {
	return xxx_messageInfo_LoadUserMsgRes.Size(m)
}
func (m *LoadUserMsgRes) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadUserMsgRes.DiscardUnknown(m)
}

var xxx_messageInfo_LoadUserMsgRes proto.InternalMessageInfo

func (m *LoadUserMsgRes) GetUser() *UserT {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *LoadUserMsgRes) GetEvents() []*EventT {
	if m != nil {
		return m.Events
	}
	return nil
}

////////////////////////////////////////////////
//系统
////////////////////////////////////////////////
type SysTimeMsg struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SysTimeMsg) Reset()         { *m = SysTimeMsg{} }
func (m *SysTimeMsg) String() string { return proto.CompactTextString(m) }
func (*SysTimeMsg) ProtoMessage()    {}
func (*SysTimeMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_149270acda60d50e, []int{6}
}

func (m *SysTimeMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysTimeMsg.Unmarshal(m, b)
}
func (m *SysTimeMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysTimeMsg.Marshal(b, m, deterministic)
}
func (m *SysTimeMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysTimeMsg.Merge(m, src)
}
func (m *SysTimeMsg) XXX_Size() int {
	return xxx_messageInfo_SysTimeMsg.Size(m)
}
func (m *SysTimeMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_SysTimeMsg.DiscardUnknown(m)
}

var xxx_messageInfo_SysTimeMsg proto.InternalMessageInfo

type SysTimeMsgRes struct {
	TimeSec              uint32   `protobuf:"varint,1,opt,name=time_sec,json=timeSec,proto3" json:"time_sec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SysTimeMsgRes) Reset()         { *m = SysTimeMsgRes{} }
func (m *SysTimeMsgRes) String() string { return proto.CompactTextString(m) }
func (*SysTimeMsgRes) ProtoMessage()    {}
func (*SysTimeMsgRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_149270acda60d50e, []int{7}
}

func (m *SysTimeMsgRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysTimeMsgRes.Unmarshal(m, b)
}
func (m *SysTimeMsgRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysTimeMsgRes.Marshal(b, m, deterministic)
}
func (m *SysTimeMsgRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysTimeMsgRes.Merge(m, src)
}
func (m *SysTimeMsgRes) XXX_Size() int {
	return xxx_messageInfo_SysTimeMsgRes.Size(m)
}
func (m *SysTimeMsgRes) XXX_DiscardUnknown() {
	xxx_messageInfo_SysTimeMsgRes.DiscardUnknown(m)
}

var xxx_messageInfo_SysTimeMsgRes proto.InternalMessageInfo

func (m *SysTimeMsgRes) GetTimeSec() uint32 {
	if m != nil {
		return m.TimeSec
	}
	return 0
}

func init() {
	proto.RegisterEnum("pb_mars.CMD", CMD_name, CMD_value)
	proto.RegisterType((*LoginMsg)(nil), "pb_mars.login_msg")
	proto.RegisterType((*LoginMsgRes)(nil), "pb_mars.login_msg_res")
	proto.RegisterType((*CreateRoleMsg)(nil), "pb_mars.create_role_msg")
	proto.RegisterType((*CreateRoleMsgRes)(nil), "pb_mars.create_role_msg_res")
	proto.RegisterType((*LoadUserMsg)(nil), "pb_mars.load_user_msg")
	proto.RegisterType((*LoadUserMsgRes)(nil), "pb_mars.load_user_msg_res")
	proto.RegisterType((*SysTimeMsg)(nil), "pb_mars.sys_time_msg")
	proto.RegisterType((*SysTimeMsgRes)(nil), "pb_mars.sys_time_msg_res")
}

func init() { proto.RegisterFile("pb_account.proto", fileDescriptor_149270acda60d50e) }

var fileDescriptor_149270acda60d50e = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x86, 0xe9, 0x1a, 0x2d, 0xeb, 0x29, 0x25, 0x99, 0x2b, 0x44, 0xb6, 0xab, 0xca, 0x08, 0x29,
	0x9a, 0x44, 0x2f, 0xc6, 0x13, 0x4c, 0x4d, 0x98, 0x26, 0x35, 0x54, 0x72, 0xca, 0x05, 0x17, 0xc8,
	0x72, 0x52, 0xd3, 0x56, 0x4a, 0xe2, 0xc8, 0x76, 0x41, 0x5c, 0x52, 0x5e, 0x8c, 0x47, 0x43, 0x3e,
	0x4d, 0x23, 0xd8, 0x5d, 0xbe, 0xf3, 0xfd, 0xf9, 0x8f, 0x9d, 0x40, 0xd8, 0x16, 0x5c, 0x94, 0xa5,
	0x3a, 0x34, 0x76, 0xde, 0x6a, 0x65, 0x15, 0xf1, 0xdb, 0x82, 0xd7, 0x42, 0x9b, 0xdb, 0xa0, 0x2d,
	0x78, 0xa9, 0xea, 0x5a, 0x35, 0x27, 0x43, 0xbf, 0xc2, 0xa8, 0x52, 0xdb, 0x7d, 0xc3, 0x6b, 0xb3,
	0x25, 0xb7, 0x70, 0xd5, 0x56, 0xc2, 0x7e, 0x53, 0xba, 0x8e, 0x06, 0xb3, 0x41, 0x3c, 0x61, 0x3d,
	0x93, 0x08, 0xfc, 0xae, 0x33, 0xba, 0x98, 0x0d, 0xe2, 0x11, 0x3b, 0x23, 0xbe, 0x25, 0x8c, 0xf9,
	0xa1, 0xf4, 0x26, 0x1a, 0xa2, 0xea, 0x99, 0xde, 0xc1, 0xa4, 0xaf, 0xe7, 0x5a, 0x1a, 0x72, 0x03,
	0x57, 0x3b, 0x61, 0xb8, 0x56, 0x95, 0xec, 0x56, 0xf8, 0x3b, 0x61, 0x98, 0xaa, 0x24, 0x7d, 0x07,
	0x41, 0xa9, 0xa5, 0xb0, 0x12, 0x2d, 0x1e, 0x88, 0x80, 0xd7, 0x88, 0xfa, 0x94, 0x1c, 0x31, 0x7c,
	0xa6, 0xaf, 0x61, 0xfa, 0x2c, 0xe6, 0x8a, 0x69, 0xe0, 0x36, 0x89, 0x0d, 0x3f, 0x18, 0xa9, 0xdd,
	0x90, 0x16, 0x70, 0xfd, 0xdf, 0x00, 0xd7, 0xbf, 0x05, 0xcf, 0x31, 0x16, 0x8e, 0xef, 0x83, 0x79,
	0xf7, 0x5d, 0xe6, 0x18, 0xb2, 0x0c, 0x25, 0x89, 0xe1, 0x52, 0x7e, 0x97, 0x8d, 0x35, 0xd1, 0xc5,
	0x6c, 0x18, 0x8f, 0xef, 0xc3, 0x3e, 0x86, 0x63, 0x6e, 0x59, 0xe7, 0xe9, 0x2b, 0x78, 0x69, 0x7e,
	0x1a, 0x6e, 0xf7, 0x35, 0x1e, 0x84, 0xbe, 0x87, 0xf0, 0x5f, 0x3e, 0xdf, 0x18, 0xd9, 0xc8, 0xf2,
	0x7c, 0x63, 0xc7, 0xb9, 0x2c, 0xef, 0x2c, 0x0c, 0x17, 0x59, 0x42, 0xc6, 0xe0, 0x2f, 0xb2, 0x84,
	0x27, 0xe9, 0xc7, 0xf0, 0x05, 0x99, 0xc2, 0xc4, 0xc1, 0x72, 0xf5, 0xf8, 0xf4, 0x89, 0x67, 0xf9,
	0x63, 0xf8, 0xeb, 0xe8, 0x91, 0x1b, 0x98, 0xba, 0xe1, 0x82, 0xa5, 0x0f, 0xeb, 0x94, 0xb3, 0xd5,
	0x32, 0x45, 0x75, 0x3c, 0x7a, 0xe4, 0x0d, 0x5c, 0x9f, 0xf2, 0x0f, 0x09, 0xff, 0x9c, 0xa7, 0x0c,
	0xc5, 0x6f, 0x14, 0xa1, 0x13, 0xf9, 0x97, 0x9c, 0xaf, 0x9f, 0xb2, 0xb4, 0xeb, 0xfa, 0xe3, 0x15,
	0x97, 0xf8, 0xe7, 0x3f, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x19, 0x9e, 0xda, 0x75, 0x27, 0x02,
	0x00, 0x00,
}
