// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb_common.proto

package pb_mars

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

//////////////////////////////////////////////
//错误码
//////////////////////////////////////////////
type E_ERROR_CODE int32

const (
	E_ERROR_CODE_E_ERROR_CODE_DEF     E_ERROR_CODE = 0
	E_ERROR_CODE_EC_SMS_SENDING       E_ERROR_CODE = 10000
	E_ERROR_CODE_EC_SMS_REGISTER_CODE E_ERROR_CODE = 10001
	E_ERROR_CODE_EC_USER_EXIST        E_ERROR_CODE = 10002
	E_ERROR_CODE_EC_PHONE_NUM_BIND    E_ERROR_CODE = 10003
	E_ERROR_CODE_EC_PHONE_NUM_NO_BIND E_ERROR_CODE = 10004
)

var E_ERROR_CODE_name = map[int32]string{
	0:     "E_ERROR_CODE_DEF",
	10000: "EC_SMS_SENDING",
	10001: "EC_SMS_REGISTER_CODE",
	10002: "EC_USER_EXIST",
	10003: "EC_PHONE_NUM_BIND",
	10004: "EC_PHONE_NUM_NO_BIND",
}

var E_ERROR_CODE_value = map[string]int32{
	"E_ERROR_CODE_DEF":     0,
	"EC_SMS_SENDING":       10000,
	"EC_SMS_REGISTER_CODE": 10001,
	"EC_USER_EXIST":        10002,
	"EC_PHONE_NUM_BIND":    10003,
	"EC_PHONE_NUM_NO_BIND": 10004,
}

func (x E_ERROR_CODE) String() string {
	return proto.EnumName(E_ERROR_CODE_name, int32(x))
}

func (E_ERROR_CODE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e6dfd5ec230870c6, []int{0}
}

//用户事件
type USER_EVENT_TYPE int32

const (
	USER_EVENT_TYPE_USER_EVENT_TYPE_DEF USER_EVENT_TYPE = 0
	//----------------------------------------------------------------------------
	//每日事件 DAILY_EVENT_XX
	USER_EVENT_TYPE_DAILY_EVENT_BEGIN USER_EVENT_TYPE = 100000
	USER_EVENT_TYPE_DAILY_EVENT_END   USER_EVENT_TYPE = 199999
	//----------------------------------------------------------------------------
	//每周事件 WEEKLY_EVENT_XX
	USER_EVENT_TYPE_WEEKLY_EVENT_BEGIN USER_EVENT_TYPE = 200000
	USER_EVENT_TYPE_WEEKLY_EVENT_END   USER_EVENT_TYPE = 299999
	//----------------------------------------------------------------------------
	//每月事件 MONTHLY_EVENT_XX
	USER_EVENT_TYPE_MONTHLY_EVENT_BEGIN USER_EVENT_TYPE = 300000
	USER_EVENT_TYPE_MONTHLY_EVENT_END   USER_EVENT_TYPE = 399999
	//----------------------------------------------------------------------------
	//永久事件 FOREVER_EVENT_XX
	USER_EVENT_TYPE_FOREVER_EVENT_BEGIN USER_EVENT_TYPE = 400000
	USER_EVENT_TYPE_FOREVER_EVENT_END   USER_EVENT_TYPE = 499999
	//----------------------------------------------------------------------------
	//过期事件 EXPRIE_EVENT_XX
	USER_EVENT_TYPE_EXPRIE_EVENT_BEGIN USER_EVENT_TYPE = 500000
	USER_EVENT_TYPE_EXPRIE_EVENT_END   USER_EVENT_TYPE = 599999
)

var USER_EVENT_TYPE_name = map[int32]string{
	0:      "USER_EVENT_TYPE_DEF",
	100000: "DAILY_EVENT_BEGIN",
	199999: "DAILY_EVENT_END",
	200000: "WEEKLY_EVENT_BEGIN",
	299999: "WEEKLY_EVENT_END",
	300000: "MONTHLY_EVENT_BEGIN",
	399999: "MONTHLY_EVENT_END",
	400000: "FOREVER_EVENT_BEGIN",
	499999: "FOREVER_EVENT_END",
	500000: "EXPRIE_EVENT_BEGIN",
	599999: "EXPRIE_EVENT_END",
}

var USER_EVENT_TYPE_value = map[string]int32{
	"USER_EVENT_TYPE_DEF": 0,
	"DAILY_EVENT_BEGIN":   100000,
	"DAILY_EVENT_END":     199999,
	"WEEKLY_EVENT_BEGIN":  200000,
	"WEEKLY_EVENT_END":    299999,
	"MONTHLY_EVENT_BEGIN": 300000,
	"MONTHLY_EVENT_END":   399999,
	"FOREVER_EVENT_BEGIN": 400000,
	"FOREVER_EVENT_END":   499999,
	"EXPRIE_EVENT_BEGIN":  500000,
	"EXPRIE_EVENT_END":    599999,
}

func (x USER_EVENT_TYPE) String() string {
	return proto.EnumName(USER_EVENT_TYPE_name, int32(x))
}

func (USER_EVENT_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e6dfd5ec230870c6, []int{1}
}

////////////////////////////////////////////////////
//结构体
////////////////////////////////////////////////////
//用户数据
type UserT struct {
	Uid                  uint32   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserT) Reset()         { *m = UserT{} }
func (m *UserT) String() string { return proto.CompactTextString(m) }
func (*UserT) ProtoMessage()    {}
func (*UserT) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6dfd5ec230870c6, []int{0}
}

func (m *UserT) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserT.Unmarshal(m, b)
}
func (m *UserT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserT.Marshal(b, m, deterministic)
}
func (m *UserT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserT.Merge(m, src)
}
func (m *UserT) XXX_Size() int {
	return xxx_messageInfo_UserT.Size(m)
}
func (m *UserT) XXX_DiscardUnknown() {
	xxx_messageInfo_UserT.DiscardUnknown(m)
}

var xxx_messageInfo_UserT proto.InternalMessageInfo

func (m *UserT) GetUid() uint32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *UserT) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

//事件
type EventT struct {
	Type                 uint32   `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Id                   uint32   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Data                 uint32   `protobuf:"varint,3,opt,name=data,proto3" json:"data,omitempty"`
	Time                 uint32   `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`
	StrData              string   `protobuf:"bytes,5,opt,name=strData,proto3" json:"strData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventT) Reset()         { *m = EventT{} }
func (m *EventT) String() string { return proto.CompactTextString(m) }
func (*EventT) ProtoMessage()    {}
func (*EventT) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6dfd5ec230870c6, []int{1}
}

func (m *EventT) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventT.Unmarshal(m, b)
}
func (m *EventT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventT.Marshal(b, m, deterministic)
}
func (m *EventT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventT.Merge(m, src)
}
func (m *EventT) XXX_Size() int {
	return xxx_messageInfo_EventT.Size(m)
}
func (m *EventT) XXX_DiscardUnknown() {
	xxx_messageInfo_EventT.DiscardUnknown(m)
}

var xxx_messageInfo_EventT proto.InternalMessageInfo

func (m *EventT) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *EventT) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EventT) GetData() uint32 {
	if m != nil {
		return m.Data
	}
	return 0
}

func (m *EventT) GetTime() uint32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *EventT) GetStrData() string {
	if m != nil {
		return m.StrData
	}
	return ""
}

////////////////////////////////////////////////////
//道具
////////////////////////////////////////////////////
type ItemT struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Cnt                  uint32   `protobuf:"varint,2,opt,name=cnt,proto3" json:"cnt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemT) Reset()         { *m = ItemT{} }
func (m *ItemT) String() string { return proto.CompactTextString(m) }
func (*ItemT) ProtoMessage()    {}
func (*ItemT) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6dfd5ec230870c6, []int{2}
}

func (m *ItemT) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemT.Unmarshal(m, b)
}
func (m *ItemT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemT.Marshal(b, m, deterministic)
}
func (m *ItemT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemT.Merge(m, src)
}
func (m *ItemT) XXX_Size() int {
	return xxx_messageInfo_ItemT.Size(m)
}
func (m *ItemT) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemT.DiscardUnknown(m)
}

var xxx_messageInfo_ItemT proto.InternalMessageInfo

func (m *ItemT) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ItemT) GetCnt() uint32 {
	if m != nil {
		return m.Cnt
	}
	return 0
}

func init() {
	proto.RegisterEnum("pb_mars.E_ERROR_CODE", E_ERROR_CODE_name, E_ERROR_CODE_value)
	proto.RegisterEnum("pb_mars.USER_EVENT_TYPE", USER_EVENT_TYPE_name, USER_EVENT_TYPE_value)
	proto.RegisterType((*UserT)(nil), "pb_mars.user_t")
	proto.RegisterType((*EventT)(nil), "pb_mars.event_t")
	proto.RegisterType((*ItemT)(nil), "pb_mars.item_t")
}

func init() { proto.RegisterFile("pb_common.proto", fileDescriptor_e6dfd5ec230870c6) }

var fileDescriptor_e6dfd5ec230870c6 = []byte{
	// 444 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0x4f, 0x6e, 0xd3, 0x40,
	0x14, 0xc6, 0x71, 0x52, 0x12, 0xf1, 0x94, 0x34, 0xd3, 0x97, 0xd2, 0xba, 0x9b, 0xaa, 0x8a, 0x58,
	0x54, 0x59, 0x74, 0xc3, 0x09, 0x68, 0xfc, 0x9a, 0x5a, 0x90, 0x71, 0x34, 0x76, 0x4b, 0xbb, 0x7a,
	0x4a, 0x9a, 0x59, 0x78, 0xe1, 0x38, 0x4a, 0xa6, 0x48, 0xec, 0xb8, 0x00, 0x12, 0xff, 0x56, 0x65,
	0x01, 0x2b, 0x7a, 0x01, 0x58, 0x83, 0x7a, 0x01, 0x8e, 0x00, 0x37, 0x01, 0x8d, 0xed, 0xb6, 0x71,
	0x76, 0xdf, 0xbc, 0x6f, 0x7e, 0xdf, 0xfb, 0x46, 0x1a, 0x68, 0xcd, 0xc6, 0x7c, 0x91, 0x26, 0x49,
	0x3a, 0x3d, 0x98, 0xcd, 0x53, 0x93, 0x62, 0x7d, 0x36, 0xe6, 0x64, 0x34, 0x5f, 0x74, 0x0e, 0xa0,
	0x76, 0xb9, 0xd0, 0x73, 0x36, 0x28, 0xa0, 0x7a, 0x19, 0x4f, 0x5c, 0x67, 0xcf, 0xd9, 0x6f, 0x2a,
	0x2b, 0x11, 0x61, 0x6d, 0x3a, 0x4a, 0xb4, 0x5b, 0xd9, 0x73, 0xf6, 0x1f, 0xa9, 0x4c, 0x77, 0x52,
	0xa8, 0xeb, 0x57, 0x7a, 0x6a, 0xd8, 0x58, 0xdb, 0xbc, 0x9e, 0xe9, 0x82, 0xc8, 0x34, 0xae, 0x43,
	0x25, 0x9e, 0x64, 0x40, 0x53, 0x55, 0xf2, 0x88, 0xc9, 0xc8, 0x8c, 0xdc, 0x6a, 0x7e, 0xc7, 0xea,
	0x8c, 0x8b, 0x13, 0xed, 0xae, 0x15, 0x5c, 0x9c, 0x68, 0x74, 0xa1, 0xbe, 0x30, 0x73, 0xcf, 0x5e,
	0x7d, 0x98, 0x6d, 0xbb, 0x3d, 0x76, 0xba, 0x50, 0x8b, 0x8d, 0x4e, 0xd8, 0x14, 0xd9, 0xce, 0x5d,
	0xb6, 0x80, 0xea, 0xc5, 0xd4, 0x14, 0xcb, 0xac, 0xec, 0x7e, 0x76, 0xa0, 0x41, 0x4c, 0x4a, 0x05,
	0x8a, 0x7b, 0x81, 0x47, 0xb8, 0x09, 0x62, 0xf9, 0xcc, 0x1e, 0x1d, 0x89, 0x07, 0xd8, 0x86, 0x75,
	0xea, 0x71, 0x38, 0x08, 0x39, 0x24, 0xe9, 0xf9, 0xb2, 0x2f, 0xde, 0x49, 0xdc, 0x81, 0xcd, 0x62,
	0xa8, 0xa8, 0xef, 0x87, 0x11, 0xe5, 0x88, 0x78, 0x2f, 0x11, 0xa1, 0x49, 0x3d, 0x3e, 0x09, 0x49,
	0x31, 0x9d, 0xf9, 0x61, 0x24, 0x3e, 0x48, 0xdc, 0x82, 0x0d, 0xea, 0xf1, 0xf0, 0x38, 0x90, 0xc4,
	0xf2, 0x64, 0xc0, 0x87, 0xbe, 0xf4, 0xc4, 0xc7, 0xdb, 0x98, 0xfb, 0xb9, 0x0c, 0x72, 0xeb, 0x93,
	0xec, 0x7e, 0xab, 0x40, 0x2b, 0x0f, 0x39, 0x25, 0x19, 0x71, 0x74, 0x3e, 0x24, 0xdc, 0x86, 0xf6,
	0xca, 0xa8, 0xe8, 0xb8, 0x0d, 0x1b, 0xde, 0x33, 0xff, 0xc5, 0x79, 0xe1, 0x1c, 0x52, 0xdf, 0x97,
	0xe2, 0xeb, 0xdb, 0x1a, 0x3e, 0x86, 0xd6, 0xb2, 0x41, 0xd2, 0x13, 0x3f, 0xaf, 0x1a, 0xe8, 0x02,
	0xbe, 0x24, 0x7a, 0xbe, 0x02, 0xfc, 0xba, 0x6a, 0xe0, 0x16, 0x88, 0x92, 0x63, 0x89, 0x3f, 0xd7,
	0x88, 0x3b, 0xd0, 0x1e, 0x04, 0x32, 0x3a, 0x5e, 0x41, 0xfe, 0x5e, 0xa3, 0x5d, 0x5e, 0xb6, 0x2c,
	0xf3, 0xef, 0xbb, 0x6b, 0x99, 0xa3, 0x40, 0xd1, 0xe9, 0x5d, 0xe3, 0x9c, 0x79, 0xf3, 0xc3, 0xb5,
	0x4c, 0xd9, 0xb2, 0xcc, 0x97, 0x9b, 0x5d, 0xdb, 0x8c, 0xce, 0x86, 0xca, 0xa7, 0xf2, 0x53, 0x6e,
	0x76, 0x6d, 0xb3, 0x92, 0x93, 0xbd, 0xe5, 0xf7, 0x93, 0x71, 0x2d, 0xfb, 0xa3, 0x4f, 0xff, 0x07,
	0x00, 0x00, 0xff, 0xff, 0x8e, 0xd2, 0xdb, 0x0c, 0xb6, 0x02, 0x00, 0x00,
}
